In [1]:
import os
import pandas as pd

In [3]:
category = 'Games'

signal = 'like'

num_candidates = 20

candidates_path = '/sise/bshapira-group/lilachzi/models/LlamaRec/data/preprocessed'
candidates_path = os.path.join(candidates_path, f'ciao_{category}_{signal}')

**Validation candidates**

In [4]:
val_cands = pd.read_csv(os.path.join(candidates_path, f'valid_{num_candidates}_candidates.csv'))

In [5]:
val_cands

,product_id,voter_id,candidates,y_true
0,42,2628,"{239042: 0.0, 283455: 0.0, 300170: 0.0, 279954...","{279909: 4, 239042: 0, 279954: 0, 283455: 0, 3..."
1,42,5618,"{279954: 4.0, 300170: 0.0, 239042: 0.0, 283455...","{279954: 4, 239042: 0, 279909: 0, 283455: 0, 3..."
2,42,13861,"{283455: 2.0, 300170: 3.5, 279909: 3.5, 279954...","{239042: 3.5, 279909: 3.5, 279954: 3.5, 300170..."
3,42,19606,"{239042: 0.0, 283455: 0.0, 300170: 0.0, 279909...","{279954: 4, 239042: 0, 279909: 0, 283455: 0, 3..."
4,42,5017281,"{279954: 4.0, 239042: 0.0, 283455: 0.0, 300170...","{279954: 4, 239042: 0, 279909: 0, 283455: 0, 3..."
...,...,...,...,...
15824,107608,5013856,"{271907: 4.0, 262210: 0.0, 272198: 0.0, 252772...","{239055: 4, 271907: 4, 252772: 0, 262210: 0, 2..."
15825,107608,5021102,"{272198: 0.0, 296881: 0.0, 271907: 0.0, 272624...","{298667: 4, 239055: 0, 252772: 0, 262210: 0, 2..."
15826,107608,5027154,"{272198: 4.0, 239055: 0.0, 296881: 0.0, 298667...","{272198: 4, 239055: 0, 252772: 0, 262210: 0, 2..."
15827,107608,5030710,"{262210: 4.0, 239055: 0.0, 272198: 0.0, 298667...","{262210: 4, 239055: 0, 252772: 0, 271907: 0, 2..."
15828,107608,5085480,"{262210: 4.0, 239055: 0.0, 252772: 0.0, 272198...","{262210: 4, 239055: 0, 252772: 0, 271907: 0, 2..."